### PR TITLE
Park structure branch

### PR DESCRIPTION
**Pull request by TAhub**
Refactored the code to add a new "Park" structure, instead of just using arrays of trails.
Also added a filter button, to turn unrated trails on/off.

### CODE REVIEW

**Comment by EricMentele** [comment]
Checking this out now.

**Comment by EricMentele** [comment]
One thing that is off but can be fixed in the future is that the search still shoes all parks when the filter is applied.

**Comment by TAhub** [comment]
The filter is a temporary feature that we are probably going to remove before the release version. I don't see the need to fix small details, it just means we will have more to undo later.

**Comment by EricMentele** [comment]
Good point. I see.

**Comment by EricMentele** [comment]
Great. I see the comment about that in the code now. I have tested this and it all seems good. The code is looking great so far. I will merge this now. Got this weird console output when using the camera to take a new picture to share: 

2016-03-29 20:42:46.196 Seattle Trails[2738:1432614] Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.

**Pull request merged**
