### PR TITLE
Social share branch

### PR DESCRIPTION
**Pull request by TAhub**
Okay, try two.

### CODE REVIEW

**Comment by EricMentele** [comment]
Future minor refinements: Park name selection needs some lipstick. Change from photo of to photo from.

**Comment by TAhub** [comment]
I also probably want a "select a photo" default image instead of just a white rectangle, too.

**Comment by EricMentele** [comment]
Sure! After testing both it shares fine; however, Facebook does not include the park name or hashtag.

**Comment by EricMentele** [comment]
Will merge when alert view for social sign in is dismissible.

**Comment by EricMentele** [comment]
Tested on multiple devices. Working properly. Needs some UI updates.

**Pull request merged**
