### PR TITLE
UIActivityViewController branch

### PR DESCRIPTION
**Pull request by TAhub**
I switched our social from a custom view to the UIActivityViewController. It probably needs more sophisticated testing, but it seems to work so far.
I didn't touch the storyboard at all, in case someone else is working with that. If we do go with this, we will want to remove the social page from the storyboard, eventually.

### CODE REVIEW

**Comment by EricMentele** [comment]
## On it!

Sorry for the delay.

**Comment by EricMentele** [comment]
I see that you wrote a selection alert that is duplicate code. The image picker extension gives you an alert that does the exact same thing but with titles that follow ios defaults. self.imagePicker.presentImageSourceSelectionView. This also calls presentImagePickerWithSourceType.

If you think there is a better way than this extension I'm game for a better reusable solution in order to adhere to the DRY principle. I just realized that my method description ("Presents the photo library or a selection view for that or the camera if the latter is available.") is confusingly written and doesn't make it clear that it presents a photo source selection option. I'd like to keep the alert views as alerts rather than selection menus if possible. I think selection would be good to tie to the class it relates to.

What do you think about this?

**Comment by EricMentele** [comment]
Also the image picker extension may appear a little verbose because I used generics in order to make it reusable by multiple view controllers. Now that we have eliminated the need for photo library use by issue reporting, it could be made more specific. It is nice to have highly reusable code though.

**Comment by EricMentele** [comment]
PS. I am not in total opposition to your solution here and am willing to ditch a picker extension if it makes more sense. I do want to make sure we pick one and remove unused code. Is the social controller code still being used at all or can we cut it? I will take a closer look and test more on my phone in a minute; however, at a glance it looks like your new solution replaces it.

**Comment by TAhub** [comment]
Oh, I didn't notice your function. I'll switch over to that.

**Comment by TAhub** [comment]
Aaah, it's a private function for some reason. No wonder I didn't see it.

**Comment by EricMentele** [comment]
It is private because presentImageSourceView calls it if the device has a camera or it just presents the library. I figure it is good to skip the step of selecting a source if there is only one to choose. I'll change that real quick and merge.

**Comment by EricMentele** [comment]
I updated that function and it's call. Right now I am testing and there is a horrendous delay between selecting a service and the message view appearing. Trying to figure out how to at least show the progress indicator for that.

**Comment by EricMentele** [comment]
@TAhub please take a look at my changes and let me know what you think. It literally takes 5 seconds to present an option after being selected so I started the progress spinner until the post is complete.

**Comment by EricMentele** [comment]
It's not a crazy amount of time but the user should know that something is happening after an option is selected and I could not find a way to reduce the time as it seems to be controlled by Apple's class. It does freeze the UI though so it might be that we are not using it right...

**Comment by TAhub** [comment]
Yeah, this all looks good.

**Pull request merged**
