### PR TITLE
Af networking branch

### PR DESCRIPTION
**Pull request by TAhub**
Switched from the default networking to AFNetworking. The main offshoot here is it can detect if you switch the internet on in-app (ie with airplane mode, whatever).
This is a lot of extra code, and it required adding CocoaPods, so it may not be worth it to actually go with this. I'm still not entirely sure.

### CODE REVIEW

**Comment by EricMentele** [comment]
Since this project is in Swift wouldn't it be better to use the Swift version of AFNetworking? I thought I mentioned this, Alamo Fire. What do you think?

**Comment by EricMentele** [comment]
```Network Reachability

The NetworkReachabilityManager listens for reachability changes of hosts and addresses for both WWAN and WiFi network interfaces.

let manager = NetworkReachabilityManager(host: "www.apple.com")

manager?.listener = { status in
    print("Network Status Changed: (status)")
}

manager?.startListening()
Make sure to remember to retain the manager in the above example, or no status changes will be reported.
There are some important things to remember when using network reachability to determine what to do next.

Do NOT use Reachability to determine if a network request should be sent.
You should ALWAYS send it.
When Reachability is restored, use the event to retry failed network requests.
Even though the network requests may still fail, this is a good moment to retry them.
The network reachability status can be useful for determining why a network request may have failed.
If a network request fails, it is more useful to tell the user that the network request failed due to being offline rather than a more technical errror, such as "request timed out."
It is recommended to check out WWDC 2012 Session 706, "Networking Best Practices" for more info.```

**Comment by EricMentele** [comment]
Anyway, will or did it reduce or make the existing network code better? If all it was able to provide was airplane mode handling than you may be right and we should not include such a huge dependancy. Maybe this is best for apps with more complex networking needs. You put the time into adding it and researched it's value to the app in the process though. If you think it is worth having then I will merge it. If we won't use 90% of the code being added then maybe you're right that it isn't worth it. Nearly 10k lines of code is a ton.

**Comment by TAhub** [comment]
Yeah, this probably isn't worth it.

**Pull request closed without merging**
