### PR TITLE
Update email forms and alerts

### PR DESCRIPTION
**Pull request by EricMentele**
Not sure where the merge conflict is; however it works. Please check out and review @TAhub or @David-Wolgemuth and I can resolve the conflict if you approve.

### CODE REVIEW

**Comment by TAhub** [comment]
You don't seem to be attaching the issueID to the mail body anywhere I can see.
I think the "Drive to Park" option on the action sheet would be better phrased "Driving Directions"
Also, it should be a left callout button, not a right button, because some of the park names are long enough that when the map zooms in the right side of the callout is a bit offscreen.

Looks good overall though.

**Comment by EricMentele** [comment]
It's in the subject line. Probably good to put it in the body I suppose. Cool.

**Comment by EricMentele** [comment]
Good change ideas.

**Comment by EricMentele** [comment]
The way it is implemented you can press anywhere on the annotation. The callout button just makes it apparent that there is interaction available; however, I think you're right about putting it on the left side.

**Pull request merged**
